# Generated by Django 5.0.1 on 2024-01-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_remove_user_gender_alter_user_agency_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buse',
            name='Bus_layout_id',
        ),
        migrations.RemoveField(
            model_name='buse',
            name='agency_id',
        ),
        migrations.DeleteModel(
            name='Bus_layout',
        ),
        migrations.DeleteModel(
            name='Buse',
        ),
    ]
