# Generated by Django 5.0.1 on 2024-01-30 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_remove_buse_bus_layout_id_remove_buse_agency_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nub_seats', models.CharField(max_length=100)),
                ('layout', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Buse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_type', models.CharField(max_length=100)),
                ('bus_number', models.CharField(max_length=100)),
                ('nub_seats', models.CharField(max_length=100)),
                ('Bus_layout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.bus_layout')),
                ('agency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.agency')),
            ],
        ),
    ]
