# Generated by Django 5.0.1 on 2024-01-30 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_bus_layout_buse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buse',
            new_name='Bus',
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.bus')),
            ],
        ),
    ]
