# Generated by Django 5.0.1 on 2024-01-30 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_rename_buse_bus_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_origin', models.CharField(max_length=150)),
                ('to_destination', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField(auto_now_add=True)),
                ('arrival_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('trip_cost', models.CharField(max_length=20)),
                ('bus_type', models.CharField(max_length=20)),
                ('agency_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.agency')),
                ('branch_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.branch')),
                ('bus_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.bus')),
                ('driver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
